[font]
size = 17.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"

[colors.cursor]
text = "0x0d1117"
cursor = "0xc9d1d9"

[colors.normal]
black = "0x484f58"
red = "0xff7b72"
green = "0x58a6ff"
yellow = "0xd29922"
blue = "0x58a6ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[colors.bright]
black = "0x6e7681"
red = "0xffa198"
green = "0x79c0ff"
yellow = "0xe3b341"
blue = "0x79c0ff"
magenta = "0xbc8cff"
cyan = "0x39c5cf"
white = "0xb1bac4"

[window.dimensions]
columns = 84
lines = 24
